// <copyright file="PostOperationcares_approvalitemgroupSetState.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>6/1/2018 10:30:51 AM</date>
// <summary>Implements the PostOperationcares_approvalitemgroupSetState Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace Cares.Crm.Plugin
{

    /// <summary>
    /// PostOperationcares_approvalitemgroupSetState Plugin.
    /// </summary>    
    public class PostOperationcares_approvalitemgroupSetState: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostOperationcares_approvalitemgroupSetState"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostOperationcares_approvalitemgroupSetState(string unsecure, string secure)
            : base(typeof(PostOperationcares_approvalitemgroupSetState))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            var pluginContext = localContext.PluginExecutionContext;
            var service = localContext.OrganizationService;
            var trace = localContext.TracingService;

            var caresHelper = new CaresHelper();

            trace.Trace("PreOperationcontactDelete Plugin Starts...");
            trace.Trace("Plugin InitiatingUserId : " + pluginContext.InitiatingUserId);
            trace.Trace("Plugin UserId : " + pluginContext.UserId);
            try
            {
                if (pluginContext.InputParameters.Contains("EntityMoniker") && pluginContext.InputParameters["EntityMoniker"] is EntityReference &&
                         ((EntityReference)pluginContext.InputParameters["EntityMoniker"]).LogicalName == "cares_approvalitemgroup")
                {
                    // Only perform this code if this is a SetState
                    if (!pluginContext.MessageName.Contains("SetState"))
                    {
                        return;
                    }

                    trace.Trace("Verified that PluginContext.InputParameters[EntityMoniker] is EntityReference and Logical Name is cares_approvalitemgroup and Message Name : " + pluginContext.MessageName);
                    var entity = (EntityReference)pluginContext.InputParameters["EntityMoniker"];
                    trace.Trace("Get Entity from (Entity)PluginContext.InputParameters[Target] and entity ID is : " + entity.Id);

                    trace.Trace("PluginContext.InputParameters[SetState] Value is : " + ((OptionSetValue)pluginContext.InputParameters["State"]).Value);

                    if (pluginContext.InputParameters.Contains("State") && ((OptionSetValue)pluginContext.InputParameters["State"]).Value == 1) // Value 1 means Deactivate
                    {
                        caresHelper.InactiveGroupApprovalItems(entity.Id, service, trace);
                    }
                }

                trace.Trace("PreOperationcontactDelete Plugin Ends with out executing PluginContext.InputParameters[EntityMoniker] is Entity Condition...");
            }
            catch (FaultException fex)
            {
                trace.Trace(fex.InnerException == null ? fex.Message : fex.InnerException.Message);
                throw new InvalidPluginExecutionException(fex.Message);
            }
            catch (Exception ex)
            {
                trace.Trace(ex.InnerException == null ? ex.Message : ex.InnerException.Message);
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
