// <copyright file="PreOperationcares_caresorderCreate.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>6/19/2018 10:53:19 AM</date>
// <summary>Implements the PreOperationcares_caresorderCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using AutoNumberGeneration;
using Microsoft.Xrm.Sdk;

namespace Cares.Crm.Plugin
{

    /// <summary>
    /// PreOperationcares_caresorderCreate Plugin.
    /// </summary>    
    public class PreOperationcares_caresorderCreate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationcares_caresorderCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PreOperationcares_caresorderCreate(string unsecure, string secure)
            : base(typeof(PreOperationcares_caresorderCreate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            var pluginContext = localContext.PluginExecutionContext;
            var service = localContext.OrganizationService;
            var trace = localContext.TracingService;

            var caresHelper = new CaresHelper();

            trace.Trace("PreOperationcares_caresorderCreate Plugin Starts...");
            trace.Trace("Plugin InitiatingUserId : " + pluginContext.InitiatingUserId);
            trace.Trace("Plugin UserId : " + pluginContext.UserId);
            trace.Trace("Plugin Depth : " + pluginContext.Depth);
            
            try
            {
                if (pluginContext.MessageName == "Create")
                {
                    trace.Trace("start create logic");
                    if (pluginContext.InputParameters.Contains("Target") && pluginContext.InputParameters["Target"] is Entity &&
                    ((Entity)pluginContext.InputParameters["Target"]).LogicalName == "cares_caresorder")
                    {
                        trace.Trace("pluginContext InputParameters Target is : " + pluginContext.InputParameters["Target"]);
                        var generateAutoNumber = new GenerateAutoNumber();
                        string nextNumber = generateAutoNumber.GetNextAvailableAutoGeneratedNumber("cares_caresorder", service, trace);
                        trace.Trace("PreOperationcares_caresorderCreate got next order number is : " + nextNumber);
                        var entity = (Entity)pluginContext.InputParameters["Target"];
                        entity.Attributes["cares_ordernumber"] = nextNumber;
                        trace.Trace("Number assigned to cares_ordernumber is: " + entity.Attributes["cares_ordernumber"]);
                        // There is a bug where a low percentage of orders do not get an order number assigned to them, temporary safety net added below
                        if(String.IsNullOrWhiteSpace(entity.Attributes["cares_ordernumber"].ToString())){
                            entity.Attributes["cares_ordernumber"] = nextNumber;
                        }
                    }
                }
                else if (pluginContext.MessageName.Contains("SetState"))
                {
                    trace.Trace("start setstate logic");
                    if (pluginContext.InputParameters.Contains("EntityMoniker") && pluginContext.InputParameters["EntityMoniker"] is EntityReference &&
                         ((EntityReference)pluginContext.InputParameters["EntityMoniker"]).LogicalName == "cares_caresorder")
                    {
                        EntityReference entityReference = (EntityReference)pluginContext.InputParameters["EntityMoniker"];
                        if (pluginContext.InputParameters.Contains("State") && ((OptionSetValue)pluginContext.InputParameters["State"]).Value == 1 
                            && pluginContext.InputParameters.Contains("Status") && ((OptionSetValue)pluginContext.InputParameters["Status"]).Value == 750760003)
                        {
                            trace.Trace("PluginContext.InputParameters[SetState] Value is : " + ((OptionSetValue)pluginContext.InputParameters["State"]).Value);
                            trace.Trace("PluginContext.InputParameters executing If State condition");
                            if (caresHelper.DeactivateOrderItems(entityReference.Id, service, trace))
                                throw new InvalidPluginExecutionException("You can not Deactivate this order because associated order items are active.");
                        }
                    }
                }
            }
            catch (FaultException fex)
            {
                trace.Trace(fex.InnerException == null ? fex.Message : fex.InnerException.Message);
                throw new InvalidPluginExecutionException(fex.Message);
            }
            catch (Exception ex)
            {
                trace.Trace(ex.InnerException == null ? ex.Message : ex.InnerException.Message);
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
