// <copyright file="PreOperationcares_caresorderDelete.cs" company="">
// Copyright (c) 2018 All Rights Reserved
// </copyright>
// <author></author>
// <date>8/6/2018 3:24:19 PM</date>
// <summary>Implements the PreOperationcares_caresorderDelete Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace Cares.Crm.Plugin
{

    /// <summary>
    /// PreOperationcares_caresorderDelete Plugin.
    /// </summary>    
    public class PreOperationcares_caresorderDelete: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationcares_caresorderDelete"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PreOperationcares_caresorderDelete(string unsecure, string secure)
            : base(typeof(PreOperationcares_caresorderDelete))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCrmPlugin(LocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException("localContext");
            }

            var pluginContext = localContext.PluginExecutionContext;
            var service = localContext.OrganizationService;
            var trace = localContext.TracingService;
           

            var caresHelper = new CaresHelper();

            trace.Trace("PostOperationcares_caresorderDelete Plugin Starts...");
            trace.Trace("Plugin InitiatingUserId : " + pluginContext.InitiatingUserId);
            trace.Trace("Plugin UserId : " + pluginContext.UserId);
            trace.Trace("Plugin Depth : " + pluginContext.Depth); 

            try
            {
                if (pluginContext.MessageName == "Delete")
                {
                    trace.Trace("start delete logic");
                    if (pluginContext.InputParameters.Contains("Target") && pluginContext.InputParameters["Target"] is Entity &&
                    ((Entity)pluginContext.InputParameters["Target"]).LogicalName == "cares_caresorder")
                    {
                        var entity = (Entity)pluginContext.InputParameters["Target"];
                        caresHelper.DeleteOrderItems(entity.Id, service, trace);
                    }

                }
            }
            catch (FaultException fex)
            {
                trace.Trace(fex.InnerException == null ? fex.Message : fex.InnerException.Message);
                throw new InvalidPluginExecutionException(fex.Message);
            }
            catch (Exception ex)
            {
                trace.Trace(ex.InnerException == null ? ex.Message : ex.InnerException.Message);
                throw new InvalidPluginExecutionException(ex.Message);
            }
        }
    }
}
